### ISSUE TITLE
Handling non UTF-8 files

### ISSUE THREAD

**Issue by cgestes** [dmerejkowsky/replacer#3]
calling replacer zsh sss in .config/ctafconf

I got the following backtrace with the last commits:

```
  File "/home/ctaf/.config/ctafconf/bin/replacer", line 208, in replace_in_file
    in_lines = in_fd.readlines()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid continuation byte

```

**Comment by dmerejkowsky** [comment]
Oh. This is a regression introduced by this commit: aad74e92000a1357bed881b6c3b8de760e253762

My mistake.

The previous implementation used to just skip non-utf-8 encoding files, so I'll restore that.

Better fixes could be:

- use bytes instead of strings (recent python3 versions allow regexp on bytes) (Requires #1 because life is too short)
- use chardet and preserve the encoding (if input is latin-1, output will be latin-1 too)
- add a --encoding option ?

**Comment by dmerejkowsky** [comment]
Regression fixed, keeping the issue open for discussion.

**Comment by cgestes** [comment]
Seems good enough as is.
